### ISSUE TITLE
Branch: place-constraints

### ISSUE THREAD

**Issue by acomodi** [SymbiFlow/vtr-verilog-to-routing#350] opened 2019-12-10 15:06 UTC
### Why did we need this? (what does this change enable us to do)

This enables the specification of place constraints of non-IO tiles, necessary to solve issues like https://github.com/SymbiFlow/symbiflow-arch-defs/issues/1182

### What did it change?

initial placement of fixed IOs

### Should it be merged upstream - if not, when can we delete it?
No, this is a temporary solution. The issue should be solved in a more proper way, but it requires consultations with vtr-devs to get to the final solution.

### What is needed to get this merged / deleted? 
Update VtR with an alternative solution, (e.g. enable usage of placer constraint files).

* [ ] is the implementation work to make suitable for merging / deletion completed?
* [ ] Is there an associated test? 
* [ ] is this currently part of the Conda package?
* [ ] is this properly cleaned up in our local repositories? 

### Tracker / branch / PR & other useful links
https://github.com/SymbiFlow/symbiflow-arch-defs/issues/1182

**Comment by litghost** [comment] 2020-03-04 23:34
Duplicate of #335?

**Closed as completed by litghost** 2020-03-04 23:34 UTC
Labels: wip
